second update katalon.yml

diff --git a/.github/workflows/katalon.yml b/.github/workflows/katalon.yml
--- a/.github/workflows/katalon.yml
+++ b/.github/workflows/katalon.yml
@@ -22,6 +22,26 @@ jobs:
         run: |
           wget https://github.com/katalon-studio/katalon-studio/releases/download/v10.1.0/Katalon_Studio_Engine_Linux_64-10.1.0.tar.gz
 
+      - name: Debug:Check Katalon Installation
+        run: |
+         echo "Checking workspace files..."
+         ls -la
+         echo "Checking Katalon directory..."
+         ls -la Katalon_Studio_Linux_64 || echo "Katalon_Studio_Linux_64 NOT FOUND!"
+
+      - name: Install Katalon Studio
+        run: |
+           wget -q https://download.katalon.com/9.0.0/Katalon_Studio_Linux_64-9.0.0.tar.gztar -xzf Katalon_Studio_Linux_64-9.0.0.tar.gz
+            mv Katalon_Studio_Linux_64-9.0.0 Katalon_Studio_Linux_64
+
+      - name: Run Katalon Tests
+        run: |
+         $(pwd)/Katalon_Studio_Linux_64/katalonc \
+         -noSplash -runMode=console \
+         -projectPath="$(pwd)/CrediteVile Assesment/CrediteVile Assesment.prj" \
+         -testSuitePath="Test Suites/Assessment" \
+         -browserType="Chrome"
+
       - name: Run Katalon Tests
         run: |
           ./Katalon_Studio_Linux_64/katalonc \
